### ISSUE TITLE
Autenticación y permisos

### ISSUE THREAD

**Issue by adanvillarreal** [ProyectoIntegrador2018/i2t2#27]
## Título
Autenticación y permisos

### Descripción
Diseñar e implementar la autentiación de los usuarios. Por ahora solo estarán limitados a editar sus perfiles (centros, investigadores, patentes). 

### Tareas

- [ ] Investigar posibles soluciones
- [ ] Seleccionar e implementar la solución de autenticación y permisos adecuada.

### Criterios de aceptación
- [ ] Usuarios solo pueden editar y visualizar sus perfiles.

### Recursos relacionados
- Puede que alguna gema facilite esto (e.g. https://github.com/plataformatec/devise)

**Comment by Irvel** [comment]
Duplicate of #23 ?
Closing for now
